-- MySQL Script generated by MySQL Workbench
-- Wed Sep 13 14:06:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_jardineria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_jardineria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_jardineria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_jardineria` ;

-- -----------------------------------------------------
-- Table `bd_jardineria`.`oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jardineria`.`oficina` (
  `codigo_oficina` VARCHAR(10) NOT NULL,
  `ciudad` VARCHAR(30) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `region` VARCHAR(50) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(10) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion1` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo_oficina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_jardineria`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jardineria`.`empleado` (
  `codigo_empleado` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido1` VARCHAR(50) NOT NULL,
  `apellido2` VARCHAR(50) NULL DEFAULT NULL,
  `extension` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `codigo_oficina` VARCHAR(10) NOT NULL,
  `codigo_jefe` INT NULL DEFAULT NULL,
  `puesto` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_empleado`),
  INDEX `codigo_oficina` (`codigo_oficina` ASC) VISIBLE,
  INDEX `codigo_jefe` (`codigo_jefe` ASC) VISIBLE,
  CONSTRAINT `empleado_ibfk_1`
    FOREIGN KEY (`codigo_oficina`)
    REFERENCES `bd_jardineria`.`oficina` (`codigo_oficina`),
  CONSTRAINT `empleado_ibfk_2`
    FOREIGN KEY (`codigo_jefe`)
    REFERENCES `bd_jardineria`.`empleado` (`codigo_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_jardineria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jardineria`.`cliente` (
  `codigo_cliente` INT NOT NULL,
  `nombre_cliente` VARCHAR(50) NOT NULL,
  `nombre_contacto` VARCHAR(30) NULL DEFAULT NULL,
  `apellido_contacto` VARCHAR(30) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(15) NOT NULL,
  `direccion1` VARCHAR(50) NOT NULL,
  `direccion2` VARCHAR(50) NULL DEFAULT NULL,
  `ciudad` VARCHAR(50) NOT NULL,
  `region` VARCHAR(50) NULL DEFAULT NULL,
  `pais` VARCHAR(50) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(10) NULL DEFAULT NULL,
  `codigo_empleado` INT NULL DEFAULT NULL,
  `limite_credito` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_cliente`),
  INDEX `codigo_empleado` (`codigo_empleado` ASC) VISIBLE,
  CONSTRAINT `cliente_ibfk_1`
    FOREIGN KEY (`codigo_empleado`)
    REFERENCES `bd_jardineria`.`empleado` (`codigo_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_jardineria`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jardineria`.`pedido` (
  `codigo_pedido` INT NOT NULL,
  `fecha_pedido` DATE NOT NULL,
  `fecha_esperada` DATE NOT NULL,
  `fecha_entrega` DATE NULL DEFAULT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `comentarios` VARCHAR(300) NULL DEFAULT NULL,
  `codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`codigo_pedido`),
  INDEX `codigo_cliente` (`codigo_cliente` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `bd_jardineria`.`cliente` (`codigo_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_jardineria`.`gama_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jardineria`.`gama_producto` (
  `gama` VARCHAR(50) NOT NULL,
  `descripcion_texto` VARCHAR(200) NOT NULL,
  `imagen` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`gama`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_jardineria`.`inventarios_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jardineria`.`inventarios_producto` (
  `codigo_producto` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(70) NOT NULL,
  `gama` VARCHAR(50) NOT NULL,
  `dimensiones` VARCHAR(25) NULL DEFAULT NULL,
  `proveedor` VARCHAR(50) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `cantidad_en_stock` INT NOT NULL,
  `precio_venta` DECIMAL(15,2) NOT NULL,
  `precio_proveedor` DECIMAL(15,2) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_producto`),
  INDEX `gama` (`gama` ASC) VISIBLE,
  CONSTRAINT `inventarios_producto_ibfk_1`
    FOREIGN KEY (`gama`)
    REFERENCES `bd_jardineria`.`gama_producto` (`gama`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_jardineria`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jardineria`.`detalle_pedido` (
  `codigo_pedido` INT NOT NULL,
  `codigo_producto` VARCHAR(15) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unidad` DECIMAL(15,2) NOT NULL,
  `numero_linea` INT NOT NULL,
  PRIMARY KEY (`codigo_pedido`, `codigo_producto`),
  INDEX `codigo_producto` (`codigo_producto` ASC) VISIBLE,
  CONSTRAINT `detalle_pedido_ibfk_1`
    FOREIGN KEY (`codigo_pedido`)
    REFERENCES `bd_jardineria`.`pedido` (`codigo_pedido`),
  CONSTRAINT `detalle_pedido_ibfk_2`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `bd_jardineria`.`inventarios_producto` (`codigo_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_jardineria`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jardineria`.`pago` (
  `codigo_cliente` INT NOT NULL,
  `forma_pago` VARCHAR(40) NOT NULL,
  `id_transaccion` VARCHAR(50) NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`codigo_cliente`, `id_transaccion`),
  CONSTRAINT `pago_ibfk_1`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `bd_jardineria`.`cliente` (`codigo_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
